[tool.poetry]
name = "fastapi"
version = "0.1.0"
description = ""
authors = ["Junesskim <aktpfkxl9891@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlmodel = "^0.0.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
